In [2]:
from collections import deque
import numpy as np
import random
import time
from collections import defaultdict
from sklearn.datasets import make_classification
from abc import ABC, abstractmethod
from sklearn.model_selection import train_test_split
import pandas as pd

# Find covariance of matrix

In [147]:
matrix = [[1, 2, 3], [4, 5, 6]]

In [148]:
# Calculate mean of each row
mean = []

# Change into list comprehension later
for row in matrix:
    mean_row = sum(row) / len(matrix[0])
    mean.append(mean_row)

print(mean)

[2.0, 5.0]


In [166]:
# Center each row by subtracting it's mean
centered = []

for i in range(len(matrix)):
    centered_row = []
    for j in range(len(matrix[0])):
        centered_row.append(matrix[i][j] - mean[i])

    centered.append(centered_row)

print(centered)

[[-1.0, 0.0, 1.0], [-1.0, 0.0, 1.0]]


In [ ]:
# DRY: Convert matrix[0] to a common variable

multiplied = []
for j in range(len(matrix[0])):
    product = 1
    sum = 0
    for i in range(len(matrix)):
        product *= centered[i][j]
        sum += product
    print(sum)

print(multiplied)

[0.0, 0.0, 2.0]


In [ ]:
# Covariance
covariance = sum(multiplied) / (len(multiplied) - 1)
print(covariance)

1.0


In [163]:
np.cov(matrix)

array([[1., 1.],
       [1., 1.]])

# Eigen values and eigenvectors

In [139]:
matrix = [[2, 1], [1, 2]]
n = len(matrix)
print(matrix)
print(n)

[[2, 1], [1, 2]]
2


In [136]:
identity = []
for i in range(n):
    row = []
    for j in range(n):
        row.append(1 if i == j else 0)
    identity.append(row)

In [137]:
print(identity)

[[1, 0], [0, 1]]


In [ ]:
# Use quadratic equation to solve for lambda (eigenvalue)
## Store quadratic equation variables first
a = 1
b = -matrix[0][0] - matrix[1][1]
c = matrix[0][0] * matrix[1][1] - matrix[0][1] * matrix[1][0]
print(a)
print(b)
print(c)

## Calc lambda
lambda_1 = (-b + np.sqrt(b**2 - 4 * a * c)) / (2 * a)
lambda_2 = (-b - np.sqrt(b**2 - 4 * a * c)) / (2 * a)

print(lambda_1)
print(lambda_2)


1
-4
3
3.0
1.0


In [145]:
eigenvalues = sorted([lambda_1, lambda_2], reverse=True)
eigenvalues

[np.float64(3.0), np.float64(1.0)]

# Multiply matrix by scalar

In [ ]:
matrix = [[1, 2, 3], [4, 5, 6]]
scalar = 2

In [116]:
n_rows = len(matrix)
n_cols = len(matrix[0])
print(n_rows)
print(n_cols)

2
3


In [119]:
for row in range(n_rows):
    for col in range(n_cols):
        matrix[row][col] *= 2

print(matrix)

[[2, 4, 6], [8, 10, 12]]


In [ ]:
list = [1, 2, 3, 4]
list = np.array(list)
list *= 2
list

array([2, 4, 6, 8])

# Calculate mean y row/col

In [ ]:
matrix = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
mode = "column"

In [106]:
# Calc mean by col
n_cols = len(matrix[0])
n_rows = len(matrix)

In [102]:
# Calc mean by row
mean = [sum(row) / len(row) for row in matrix]
mean

[2.0, 5.0, 8.0]

In [108]:
# Calc mean by col
result = []

mean = [
    sum(matrix[row][col] for row in range(n_rows)) / n_rows for col in range(n_cols)
]

for col in range(n_cols):
    column_sum = 0
    for row in range(n_rows):
        column_sum += matrix[row][col]
    mean = column_sum / n_rows
    result.append(mean)

# Reshape matrix

In [ ]:
a = [[1, 2, 3, 4], [5, 6, 7, 8]]
new_shape = (4, 2)

In [ ]:
flat = [elem for row in a for elem in row]
reshaped = [flat[i : i + 2] for i in range(0, len(flat), 2)]

In [92]:
reshaped

[[1, 2], [3, 4], [5, 6], [7, 8]]

# Transpose matrix

In [ ]:
a = [[1, 2, 3], [4, 5, 6]]
type(a)

list

In [ ]:
tranposed = []

transposed = [[a[row][col] for row in range(len(a))] for col in range(len(a[0]))]

In [84]:
transposed

[[1, 4], [2, 5], [3, 6]]

# Matrix dot vector

In [52]:
a = [[1, 2], [2, 4]]
b = [1, 2]

result = np.dot(a, b)
result

array([ 5, 10])

In [ ]:
n_rows = len(a)
n_cols = len(b)

2


In [ ]:
if n_rows != n_cols
    return -1

1

In [58]:
result = []

for row in range(len(a)):
    dot = sum(a[row][col] * b[col] for col in range(len(b)))
    result.append(dot)

print(result)

[5, 10]


# Positional encoding

In [17]:
def positional_encoding(seq_len, d_model):
    """
    Args:
        seq_len: Max sequence length
        d_model: Embedding dimension
    Returns:
        PE matrix (seq_len, d_model)
    """
    pe = np.zeros((seq_len, d_model))
    position = np.arange(seq_len).reshape(-1, 1)
    div_term = np.exp(np.arange(0, d_model, 2) * -(np.log(10000.0) / d_model))
    pe[:, 0::2] = np.sin(position * div_term)
    pe[:, 1::2] = np.cos(position * div_term)

    return pe

In [18]:
seq_len = 10
d_model = 10

In [19]:
pe = positional_encoding(10, 10)
print(pe)

[[ 0.00000000e+00  1.00000000e+00  0.00000000e+00  1.00000000e+00
   0.00000000e+00  1.00000000e+00  0.00000000e+00  1.00000000e+00
   0.00000000e+00  1.00000000e+00]
 [ 8.41470985e-01  5.40302306e-01  1.57826640e-01  9.87466836e-01
   2.51162229e-02  9.99684538e-01  3.98106119e-03  9.99992076e-01
   6.30957303e-04  9.99999801e-01]
 [ 9.09297427e-01 -4.16146837e-01  3.11697146e-01  9.50181503e-01
   5.02165994e-02  9.98738351e-01  7.96205928e-03  9.99968302e-01
   1.26191435e-03  9.99999204e-01]
 [ 1.41120008e-01 -9.89992497e-01  4.57754548e-01  8.89078609e-01
   7.52852930e-02  9.97162035e-01  1.19429312e-02  9.99928681e-01
   1.89287090e-03  9.99998209e-01]
 [-7.56802495e-01 -6.53643621e-01  5.92337725e-01  8.05689779e-01
   1.00306487e-01  9.94956586e-01  1.59236138e-02  9.99873211e-01
   2.52382670e-03  9.99996815e-01]
 [-9.58924275e-01  2.83662185e-01  7.12073170e-01  7.02105263e-01
   1.25264396e-01  9.92123395e-01  1.99040441e-02  9.99801895e-01
   3.15478149e-03  9.99995024e-01

# Self attention mechanism implementation

In [ ]:
# Why is the softmax using np.max() and not max()?
# Give me the formula for softmax, and also why axis=-1 and keepdims=True
# softmax(x) = np.exp(x)/sum(np.exp(x))
def softmax(x, axis=-1):
    exp_x = np.exp(x - np.max(x, axis=axis, keepdims=True))
    return exp_x / np.sum(exp_x, axis=axis, keepdims=True)

In [ ]:
def self_attention(X, W_q, W_k, W_v):
    """
    Args:
        X: Input matrix (seq_len, d_model)
        W_q: Query weight matrix (d_model, d_k)
        W_k: Key weight matrix (d_model, d_k)
        W_v: Value weight matrix (d_model, d_k)

    Returns:
        Output matrix (seq_len, d_v)
    """

    # Project inputs to QKV
    Q = X @ W_q
    K = X @ W_k
    V = X @ W_v

    # Calculate attention score
    d_k = Q.shape[-1]
    scores = Q @ K.T / np.sqrt(d_k)  # (seq_len, seq_len)

    # Apply softmax to get attention weights
    attention_weights = softmax(scores, axis=-1)  # (seq_len, seq_len)

    # Weighted sum of values
    output = attention_weights @ V  # (seq_len, d_v)

    return output, attention_weights

In [ ]:
def multi_head_attention(X, num_heads, W_q, W_k, W_v, W_o):
    seq_len, d_model = X.shape
    d_k = d_model // num_heads

    # Project and split into heads
    Q = (X @ W_q).reshape(seq_len, num_heads, d_k)
    K = (X @ W_k).reshape(seq_len, num_heads, d_k)
    V = (X @ W_v).reshape(seq_len, num_heads, d_k)

    # Transpose for batche computation: (num_heads, seq_len, d_k)
    Q = Q.transpose(1, 0, 2)
    K = K.transpose(1, 0, 2)
    V = V.transpose(1, 0, 2)

    # Attention per head
    scores = Q @ K.transpose(0, 2, 1) / np.sqrt(d_k)  # (num_heads, seq_len, seq_len)
    attention_weights = softmax(scores, axis=-1)
    head_outputs = attention_weights @ V  # (num_heads, seq_len, d_k)

    # Concat heads and project
    concat = head_outputs.transpose(1, 0, 2).reshape(
        seq_len, d_model
    )  # (seq_len, d_model)
    output = concat @ W_o  # (seq_len, d_model). W_o (d_model, d_model)

    return output, attention_weights

# Feature depency resolver

In [ ]:
 class FeatureDependencyResolver:
      def __init__(self, dependencies: dict):
          # Build graph structure
          pass

      def topological_sort(self) -> list:
          # Return valid computation order
          pass

      def has_cycle(self) -> bool:
          # Return True if circular dependency exists
          pass

      def compute_parallel_batches(self) -> list:
          # Return list of batches (each batch is a list of features)
          pass

In [ ]:
dependencies = {
    "raw_price": [],
    "raw_volume": [],
    "returns": ["raw_price"],
    "volatility": ["returns"],
    "volume_ma": ["raw_volume"],
    "price_volume_corr": ["returns", "volume_ma"],
    "risk_score": ["volatility", "price_volume_corr"],
}

In [271]:
# Build in-degree map
## Build a new dict that has feature as key, and the no. of dependencies as value
in_degree = {feature: len(deps) for feature, deps in dependencies.items()}
print(in_degree)

{'raw_price': 0, 'raw_volume': 0, 'returns': 1, 'volatility': 1, 'volume_ma': 1, 'price_volume_corr': 2, 'risk_score': 2}


In [272]:
# Initialize queue with zero in-degree nodes
queue = deque([feature for feature, degree in in_degree.items() if degree == 0])
print(queue)

deque(['raw_price', 'raw_volume'])


In [273]:
result = []

while queue:
    current = queue.popleft()
    result.append(current)

    # Decrease in-degree for features depending on current
    for feature, deps in dependencies.items():
        if current in deps:
            in_degree[feature] -= 1
            if in_degree[feature] == 0:
                queue.append(feature)

# Check for cycle
if len(result) != len(dependencies):
    raise ValueError("Circular dependency detected")

In [274]:
result

['raw_price',
 'raw_volume',
 'returns',
 'volume_ma',
 'volatility',
 'price_volume_corr',
 'risk_score']

In [278]:
in_degree = {feature: len(dependency) for feature, dependency in dependencies.items()}

In [ ]:
queue = deque(feature for feature, depdendency in in_degree.items() if depdendency == 0)
queue

deque(['raw_price', 'raw_volume'])

In [281]:
batch_num = {}

In [ ]:
while queue:
    current = queue.popleft()
    if not dependencies[current]:
        batch_num[current] = 0
    else:
        batch_num[current] = (
            max(batch_num[dependency] for dependency in dependencies[current]) + 1
        )

    for feature, dependency in dependencies.items():
        if current in dependency:
            in_degree[feature] -= 1
            if in_degree[feature] == 0:
                queue.append(feature)

max_batch = max(batch_num.values())
batches = [[] for _ in range(max_batch + 1)]

for feature, batch in batch_num.items():
    batches[batch].append(feature)

In [286]:
batches

[['raw_price', 'raw_volume'], ['volume_ma']]

In [ ]:
def compute_parallel_batches(dependencies: dict) -> list:
    """
    Returns list of batches where each batch can execute in parallel.
    Raises ValueError if circular dependency detected.
    """
    # Step 1: Build reverse graph (who depends on me?)
    graph = {feature: [] for feature in dependencies}
    for feature, deps in dependencies.items():
        for dep in deps:
            graph[dep].append(feature)

    # Step 2: Count incoming dependencies
    in_degree = {feature: len(deps) for feature, deps in dependencies.items()}

    # Step 3: Start with features that have no dependencies
    queue = deque([f for f, degree in in_degree.items() if degree == 0])

    # Step 4: Process in topological order, assign batch numbers
    batch_num = {}

    while queue:
        current = queue.popleft()

        # Assign batch: 0 if no deps, else max(dep batches) + 1
        if len(dependencies[current]) == 0:
            batch_num[current] = 0
        else:
            batch_num[current] = (
                max(batch_num[dep] for dep in dependencies[current]) + 1
            )

        # Reduce in-degree for features that depend on current
        for dependent in graph[current]:
            in_degree[dependent] -= 1
            if in_degree[dependent] == 0:
                queue.append(dependent)

    # Step 5: Check for cycles
    if len(batch_num) != len(dependencies):
        raise ValueError("Circular dependency detected")

    # Step 6: Group features by batch number
    max_batch = max(batch_num.values())
    batches = [[] for _ in range(max_batch + 1)]
    for feature, batch in batch_num.items():
        batches[batch].append(feature)

    return batches


def topological_sort(dependencies: dict) -> list:
    """Returns features in valid computation order."""
    batches = compute_parallel_batches(dependencies)
    return [feature for batch in batches for feature in batch]


def has_cycle(dependencies: dict) -> bool:
    """Returns True if circular dependency exists."""
    try:
        compute_parallel_batches(dependencies)
        return False
    except ValueError:
        return True

In [ ]:
dependencies = {
    "raw_price": [],
    "raw_volume": [],
    "returns": ["raw_price"],
    "volatility": ["returns"],
    "volume_ma": ["raw_volume"],
    "price_volume_corr": ["returns", "volume_ma"],
    "risk_score": ["volatility", "price_volume_corr"],
}

# Get parallel batches
batches = compute_parallel_batches(dependencies)
print(batches)

[['raw_price', 'raw_volume'], ['returns', 'volume_ma'], ['volatility', 'price_volume_corr'], ['risk_score']]


# EWM Covariance

In [255]:
returns, y = make_classification(n_features=4, random_state=42)
print(returns.shape)
print(returns[:5])

(100, 4)
[[-1.05383855 -1.02754411 -0.32929388  0.82600732]
 [ 1.56931739  1.306542   -0.23938468 -0.3313761 ]
 [-0.35885569 -0.69102126 -1.22532865  1.65214494]
 [-0.1368559   0.46093758  1.89691056 -2.2813861 ]
 [-0.04862909  0.50230075  1.77872961 -2.17105282]]


In [ ]:
def ewm_covariance(returns: np.ndarray, decay: float) -> np.ndarray:
    """
    Calculates exponentially weighted covariance matric
    Args:
        returns: Array of shape (n_days, n_assets) of daily returns
        decay: Lambda parameter
    Returns:
        Covariance matrix
    """
    # Get number of rows for weights calculation
    n_days, n_assets = returns.shape

    # Get exponents. Last row gets biggest number, oldest gets smallest
    exponents = np.arange(n_days - 1, -1, -1)

    # Calculate weights from exponents
    weights = (1 - decay) * decay**exponents

    # Normalize the weights
    weights = weights / weights.sum()

    # Calculated weighted mean
    weighted_mean = np.dot(weights, returns)

    # Get centered value
    centered = returns - weighted_mean

    # Math trick to calculate covariance
    ## Calculate sqrt weights
    sqrt_weights = np.sqrt(weights).reshape(-1, 1)
    ## Calculated centered_weighted
    centered_weighted = centered * sqrt_weights
    cov_matrix = centered_weighted.T @ centered_weighted

    return cov_matrix


In [267]:
cov_matrix = ewm_covariance(returns, decay=0.94)
cov_matrix

array([[ 1.50304966,  0.96021459, -1.17942379,  0.85269747],
       [ 0.96021459,  0.69266431, -0.49488971,  0.22630876],
       [-1.17942379, -0.49488971,  1.76931393, -1.70826046],
       [ 0.85269747,  0.22630876, -1.70826046,  1.76344153]])

# Rolling risk metrics

In [ ]:
# Input data
np.random.seed(42)
df = pd.DataFrame(
    {
        "dates": pd.date_range("2023-01-01", periods=260, freq="B"),
        "daily_return": pd.Series(np.random.normal(0.001, 0.02, 260)),
    }
)

df.tail()

dates  daily_return
255 2023-12-25     -0.008685
256 2023-12-26      0.026338
257 2023-12-27     -0.013153
258 2023-12-28      0.009876
259 2023-12-29      0.016493

In [ ]:
df["std_dev"] = df["daily_return"].rolling(window=20).std()
df["volatility"] = df["std_dev"] * np.sqrt(252)
df.tail()

dates  daily_return  volatility   std_dev
255 2023-12-25     -0.008685    0.348853  0.021976
256 2023-12-26      0.026338    0.327260  0.020615
257 2023-12-27     -0.013153    0.332429  0.020941
258 2023-12-28      0.009876    0.328648  0.020703
259 2023-12-29      0.016493    0.327788  0.020649

In [ ]:
df["mean_return"] = df["daily_return"].rolling(window=20).mean()
df["sharpe_ratio"] = df["mean_return"] / df["std_dev"] * np.sqrt(252)
df.tail()

dates  daily_return  volatility   std_dev  sharpe_ratio  mean_return
255 2023-12-25     -0.008685    0.348853  0.021976      0.094488     0.000131
256 2023-12-26      0.026338    0.327260  0.020615      2.635700     0.003423
257 2023-12-27     -0.013153    0.332429  0.020941      1.916923     0.002529
258 2023-12-28      0.009876    0.328648  0.020703      2.786730     0.003634
259 2023-12-29      0.016493    0.327788  0.020649      2.734229     0.003557

In [ ]:
df["cumulative_wealth"] = (1 + df["daily_return"]).cumprod()
df["rolling_peak"] = df["cumulative_wealth"].rolling(window=60).max()

In [ ]:
df.head(20)

dates  daily_return  volatility  ...  rolling_peak  drawdown  max_drawdown
0  2023-01-02      0.010934         NaN  ...           NaN       NaN           NaN
1  2023-01-03     -0.001765         NaN  ...           NaN       NaN           NaN
2  2023-01-04      0.013954         NaN  ...           NaN       NaN           NaN
3  2023-01-05      0.031461         NaN  ...           NaN       NaN           NaN
4  2023-01-06     -0.003683         NaN  ...           NaN       NaN           NaN
5  2023-01-09     -0.003683         NaN  ...           NaN       NaN           NaN
6  2023-01-10      0.032584         NaN  ...           NaN       NaN           NaN
7  2023-01-11      0.016349         NaN  ...           NaN       NaN           NaN
8  2023-01-12     -0.008389         NaN  ...           NaN       NaN           NaN
9  2023-01-13      0.011851         NaN  ...           NaN       NaN           NaN
10 2023-01-16     -0.008268         NaN  ...           NaN       NaN           NaN
11 2023-01-17     -0.008315         NaN  ...           NaN       NaN           NaN
12 2023-01-18      0.005839         NaN  ...           NaN       NaN           NaN
13 2023-01-19     -0.037266         NaN  ...           NaN       NaN           NaN
14 2023-01-20     -0.033498         NaN  ...           NaN       NaN           NaN
15 2023-01-23     -0.010246         NaN  ...           NaN       NaN           NaN
16 2023-01-24     -0.019257         NaN  ...           NaN       NaN           NaN
17 2023-01-25      0.007285         NaN  ...           NaN       NaN           NaN
18 2023-01-26     -0.017160         NaN  ...           NaN       NaN           NaN
19 2023-01-27     -0.027246      0.3048  ...           NaN       NaN           NaN

[20 rows x 10 columns]

In [ ]:
df["max_drawdown"] = df["drawdown"].rolling(window=60).min()

In [ ]:
print(df["max_drawdown"].min())

-0.2514226354265785


# Feature Transformer Network

In [ ]:
data = np.array([[1000, 50], [2000, 100], [1500, 75], [3000, 150]])
display(data)

array([[1000,   50],
       [2000,  100],
       [1500,   75],
       [3000,  150]])

In [ ]:
class BaseTransformer(ABC):
    """Abstract base class for all transformers"""

    @abstractmethod
    def fit(self, X):
        """Learn parameters from X. Must be implemented by subclasses"""
        pass

    @abstractmethod
    def transform(self, X):
        """Apply transformatiion using learned parameters"""
        pass

    def fit_transform(self, X):
        """Convenience method: fir then transform"""
        self.fit(X)
        return self.transform(X)

In [ ]:
class Standard_Scaler(BaseTransformer):
    """Standardize features by remvoing mean andscalingto unit  variance"""

    def __init__(self):
        self.mean_ = None
        self.std_ = None

    def fit(self, X):
        """Compute mean and std from training data"""
        X = np.array(X)

        # Compute mean and std
        self.mean_ = np.mean(X, axis=0)
        self.std_ = np.std(X, axis=0)

        # Handle edge case
        self.std_ = np.where(self.std_ == 0, 1, self.std_)

        return self  # Return self for method chaining

    def transform(self, X):
        "Apply standardization using store mean and std"
        # Check if fitted
        if self.mean_ is None or self.std_ is None:
            raise ValueError("StandardScaler is not fitted. Call fit() first")
        X = np.array(X)
        return (X - self.mean_) / self.std_

In [ ]:
class Log_Transformer(BaseTransformer):
    """Log transform doesn't need to fit anything, but we mark as fitted"""

    def __init__(self):
        self.fitted_ = False

    def fit(self, X):
        X = np.array(X)

        # Check for negative values
        if np.any(X < 0):
            raise ValueError(
                "Data contains negative values. LogTransformer does not support negative values"
            )

        self.fitted_ = True
        return self

    def transform(self, X):
        X = np.array(X)

        if not self.fitted_:
            raise ValueError("Log_Transformer not fitted. Call fit() first")

        # Check for negative values
        if np.any(X < 0):
            raise ValueError(
                "Data contains negative values. LogTransformer does not support negative values"
            )

        # Use log1p to handle 0 values better
        return np.log1p(X)

In [ ]:
class Pipeline:
    """Chain multiple transformers together"""

    def __init__(self, transformers):
        """
        Args:
            transformers: List of transformer instances
        """
        self.transformers = transformers

    def fit(self, X):
        X_transformed = np.array(X)

        for transformer in self.transformers:
            # Fit on current data
            transformer.fit(X_transformed)
            # Transform for next step
            X_transformed = transformer.transform(X_transformed)

        return self

    def transform(self, X):
        """Apply all transformers seqeuntially"""
        X_transformed = np.array(X)

        for transformer in self.transformers:
            # Transform data
            X_transformed = transformer.transform(X_transformed)

        return X_transformed

    def fit_transform(self, X):
        """Fit and transform in one step"""
        self.fit(X)
        return self.transform(X)

In [ ]:
# Create randomize train and test data
X, y = make_classification(
    n_samples=20,
    n_features=3,
    n_informative=2,
    n_redundant=0,
    n_classes=2,
    random_state=42,
)

# Create train test split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# Check shape
print(X_train.shape)
print(X_test.shape)


(16, 3)
(4, 3)


In [ ]:
transformers_list = [Log_Transformer(), Standard_Scaler()]
pipeline = Pipeline(transformers_list)

X_train_transformed = pipeline.fit_transform(abs(X_train))
X_test_transformed = pipeline.transform(abs(X_test))

[[ 0.49496127 -0.58620189  2.33381747]
 [-1.9477101   0.69235584  0.24631018]
 [-0.10264818  0.29456159 -0.71507635]
 [ 0.94379629  0.00423813  0.08123043]
 [ 0.81852484 -2.03172154  0.57664785]
 [ 0.71598007 -0.4278377   0.20482236]
 [ 0.4288094   0.88337106 -0.28583051]
 [-1.04318652 -0.13895477 -1.75341917]
 [-0.8655255   1.30749947 -0.03580836]
 [-0.7882702  -0.0225576  -0.51034099]
 [-0.96760499  0.69537306 -1.98564645]
 [ 1.29767538  1.27364641 -0.04227517]
 [ 0.88218261  1.38861043 -0.27844868]
 [-0.49086041 -1.31036187  1.09634386]
 [ 1.61595082 -1.49798179  0.97444195]
 [-0.99207477 -0.52403883  0.09323159]]


In [ ]:
scaler = Standard_Scaler()
print(scaler)

# Hashmaps to check duplicates

In [ ]:
transactions = [
    {"id": "txn_001", "user_id": "U100", "amount": 50.00, "timestamp": 1000},
    {"id": "txn_002", "user_id": "U100", "amount": 50.00, "timestamp": 1003},
    {"id": "txn_003", "user_id": "U100", "amount": 50.00, "timestamp": 1500},
    {"id": "txn_004", "user_id": "U200", "amount": 75.00, "timestamp": 1001},
    {"id": "txn_005", "user_id": "U200", "amount": 75.00, "timestamp": 1008},
    {"id": "txn_006", "user_id": "U100", "amount": 50.00, "timestamp": 1006},
]
T = 10

In [ ]:
# Function to check for duplicates in transactions
def check_transaction_duplicates(transactions: list, T: float) -> list:
    duplicate_index = []

    for i in range(len(transactions)):
        for j in range(i + 1, len(transactions)):
            txn1 = transactions[i]
            txn2 = transactions[j]

            # Check the 3 conditions
            same_user = txn1["user_id"] == txn2["user_id"]
            same_amount = txn1["amount"] == txn2["amount"]
            within_time = abs(txn1["timestamp"] - txn2["timestamp"]) <= T

            if same_user and same_amount and within_time:
                duplicate_index.append((txn1["id"], txn2["id"]))

    return duplicate_index

In [ ]:
# Complexity is O(n^2)
start_time = time.time()
duplicate_index = check_transaction_duplicates(transactions, T)
print(f"Time taken: {time.time() - start_time}")
print(duplicate_index)

Time taken: 0.00018405914306640625
[('txn_001', 'txn_002'), ('txn_001', 'txn_006'), ('txn_002', 'txn_006'), ('txn_004', 'txn_005')]


In [ ]:
groups = defaultdict(list)

for txn in transactions:
    key = (txn["user_id"], txn["amount"])
    groups[key].append(txn)

display(groups)

defaultdict(list,
            {('U100',
              50.0): [{'id': 'txn_001',
               'user_id': 'U100',
               'amount': 50.0,
               'timestamp': 1000}, {'id': 'txn_002',
               'user_id': 'U100',
               'amount': 50.0,
               'timestamp': 1003}, {'id': 'txn_003',
               'user_id': 'U100',
               'amount': 50.0,
               'timestamp': 1500}, {'id': 'txn_006',
               'user_id': 'U100',
               'amount': 50.0,
               'timestamp': 1006}],
             ('U200',
              75.0): [{'id': 'txn_004',
               'user_id': 'U200',
               'amount': 75.0,
               'timestamp': 1001}, {'id': 'txn_005',
               'user_id': 'U200',
               'amount': 75.0,
               'timestamp': 1008}]})

In [ ]:
def find_duplicate_transactions(
    transactions: list[dict], T: int
) -> list[tuple[str, str]]:
    # Step 1: Group transactions by (user_id, amount)
    groups = defaultdict(list)

    for txn in transactions:
        key = (txn["user_id"], txn["amount"])
        groups[key].append(txn)

    # Step 2: For each group, find duplicates
    duplicates = []

    for key, txn_list in groups.items():
        txn_list.sort(key=lambda x: x["timestamp"])

        for i in range(len(txn_list)):
            for j in range(i + 1, len(txn_list)):
                time_diff = txn_list[j]["timestamp"] - txn_list[i]["timestamp"]

                if time_diff > T:
                    break

                duplicates.append((txn_list[i]["id"], txn_list[j]["id"]))

    return duplicates

In [ ]:
# Complexity is O(n)
start_time = time.time()
duplicates = find_duplicate_transactions(transactions, T)
print(f"Time taken: {time.time() - start_time}")
print(duplicates)

Time taken: 0.0004107952117919922
[('txn_001', 'txn_002'), ('txn_001', 'txn_006'), ('txn_002', 'txn_006'), ('txn_004', 'txn_005')]


In [ ]:
expected = ("txn_001", "txn_002")
assert duplicates[0] == expected, f"Expected {expected}, got {duplicates[0]}"

# Price stream class

In [ ]:
class PriceStream:
    def __init__(self):
        self.prices = deque()
        self.total_sum = 0
        self.count = 0
        self.max_deque = deque()
        self.min_deque = deque()

    # Add new price
    def add(self, price) -> None:
        if isinstance(price, (list, tuple)):
            for p in price:
                self._add_single(p)
        else:
            self._add_single(price)

    # Add new price helper
    def _add_single(self, price: float) -> None:
        self.prices.append(price)
        self.total_sum += price
        self.count += 1

        # Imnplement max_deque
        while self.max_deque and self.max_deque[-1] < price:
            self.max_deque.pop()
        self.max_deque.append(price)

        # Imnplement min_deque
        while self.min_deque and self.min_deque[-1] > price:
            self.min_deque.pop()
        self.min_deque.append(price)

    # Get max price from the current stream
    def get_max(self) -> float:
        return self.max_deque[0]

    # Get min price from the current stream
    def get_min(self) -> float:
        return self.min_deque[0]

    # Get mean price from the current steam
    def get_mean(self) -> float:
        return self.total_sum / self.count

    # Remove oldest price in stream
    def remove_oldest(self) -> list:
        oldest_px = self.prices.popleft()
        self.total_sum -= oldest_px
        self.count -= 1

        if self.max_deque and self.max_deque[0] == oldest_px:
            self.prices.popleft()

        if self.min_deque and self.min_deque[0] == oldest_px:
            self.prices.popleft()

    def __repr__(self):
        return f"Current stream: {self.prices}"


In [ ]:
stream = PriceStream()

In [ ]:
stream.add(10)
stream.add(5)
stream.add(8)
stream.add(11)
stream.add([random.randint(1, 50) for _ in range(10)])
print(stream)

Current stream: deque([10, 5, 8, 11, 10, 50, 5, 26, 9, 1, 9, 16, 27, 4])


In [ ]:
max_px = stream.get_max()
print(max_px)

50


In [ ]:
min_px = stream.get_min()
print(min_px)

1


In [ ]:
mean_px = stream.get_mean()
print(mean_px)

13.642857142857142


In [ ]:
stream.remove_oldest()
print(stream)

Current stream: deque([5, 8, 11, 10, 50, 5, 26, 9, 1, 9, 16, 27, 4])


In [ ]:
mean_px = stream.get_mean()
print(mean_px)

13.923076923076923


In [ ]:
min_px = stream.get_min()
print(min_px)

1


In [ ]:
min_px = stream.get_max()
print(max_px)

50
